
#Modelado de salidas analiticas

name: "mercado"
version: "1.0.0"
config-version: 2

profile: "mercado"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  return_invalidation_days: 30
  valid_payment_statuses:
    - "confirmado"
    - "confirmed"
    - "paid_confirmed"
    - "pagado"

models:
  mercado:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +schema: staging
      +materialized: view
      +tags: ["staging", "cleaning"]

    intermediate:
      +schema: intermediate
      +materialized: view
      +tags: ["intermediate", "business_logic"]

    marts:
      +schema: marts
      +materialized: table
      +tags: ["marts", "bi_ready"]

seeds:
  mercado:
    +schema: staging

snapshots:
  mercado:
    +target_schema: snapshots

tests:
  +store_failures: true
  +schema: test_failures

quoting:
  database: false
  schema: false
  identifier: false
